import battery from "../assets/screen-post-svsKYetYPUI-unsplash.jpg";
import screen from "../assets/screen.jpg";
import port from "../assets/port.jpg";
const services = [
    {
        id: 900,
        brandType: "iPhone 15",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 901,
        brandType: "iPhone 15",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 902,
        brandType: "iPhone 15",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 903,
        brandType: "iPhone 15",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 904,
        brandType: "iPhone 15",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 905,
        brandType: "iPhone 15",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
    {
        id: 906,
        brandType: "iPhone 15 Plus",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 907,
        brandType: "iPhone 15 Plus",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 908,
        brandType: "iPhone 15 Plus",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 909,
        brandType: "iPhone 15 Plus",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 910,
        brandType: "iPhone 15 Plus",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 911,
        brandType: "iPhone 15 Plus",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
    {
        id: 912,
        brandType: "Samsung Galaxy S22",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 913,
        brandType: "Samsung Galaxy S22",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 914,
        brandType: "Samsung Galaxy S22",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 915,
        brandType: "Samsung Galaxy S22",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 916,
        brandType: "Samsung Galaxy S22",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 917,
        brandType: "Samsung Galaxy S22",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
    {
        id: 918,
        brandType: "Huawei P50",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 919,
        brandType: "Huawei P50",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 920,
        brandType: "Huawei P50",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 921,
        brandType: "Huawei P50",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 922,
        brandType: "Huawei P50",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 923,
        brandType: "Huawei P50",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
    {
        id: 924,
        brandType: "Huawei P50",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 925,
        brandType: "Huawei P50",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 926,
        brandType: "Huawei P50",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 927,
        brandType: "Huawei P50",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 928,
        brandType: "Huawei P50",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 929,
        brandType: "Huawei P50",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
    {
        id: 924,
        brandType: "Xiaomi Mi 12",
        service: "battery",
        img: battery,
        originalorafter: "original",
        price: 24000,
    },
    {
        id: 925,
        brandType: "Xiaomi Mi 12",
        service: "battery",
        img: battery,
        originalorafter: "aftermarket",
        price: 20000,
    },
    {
        id: 926,
        brandType: "Xiaomi Mi 12",
        service: "screen",
        img: screen,
        originalorafter: "original",
        price: 34000,
    },
    {
        id: 927,
        brandType: "Xiaomi Mi 12",
        service: "screen",
        img: screen,
        originalorafter: "aftermarket",
        price: 27000,
    },
    {
        id: 928,
        brandType: "Xiaomi Mi 12",
        service: "port",
        img: port,
        originalorafter: "original",
        price: 13000,
    },
    {
        id: 929,
        brandType: "Xiaomi Mi 12",
        service: "port",
        img: port,
        originalorafter: "aftermarket",
        price: 11000,
    },
];
export default services;
